url: https://sanddollarenterprises.github.io
baseurl:

# Site settings
title: Sand Dollar Enterprises
email: ceo@sanddollarenterprises.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Amy Coghlan
  pic: 1
  position: CEO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Gordon Tsui
  pic: 2
  position: CEO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Melanie Ang
  pic: 3
  position: CEO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/sanddollarent
  - title: facebook
    url: https://www.facebook.com/sanddollarenterprises/
  - title: instagram
    url: https://www.instagram.com/sanddollarenterprises/?hl=en
  - title: linkedin
    url: https://www.linkedin.com/groups/13549010

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: Vancouver, BC

# Build settings
markdown: kramdown
permalink: pretty
